# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Prueba de ingreso' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Prueba de ingreso
  pod 'Alamofire', '~> 5.4'
  pod 'Mocker'

  target 'Prueba de ingresoTests' do
    # Pods for testing
    pod 'Mocker'
    pod 'Alamofire', '~> 5.4'
  end

end
